trigger:
- master

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  BuildConfiguration: Release

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: run
    projects: Generator/*.csproj
    arguments: -c $(BuildConfiguration)
  displayName: Build and Run Statiq

- publish: Generator/output
  artifact: website
  displayName: Publish Artifacts