trigger:
- master

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BuildConfiguration: Release

steps:

- task: UseDotNet@2
  displayName: Use .NET Core 3.1.x SDK
  inputs:
    version: 3.1.x

- task: DotNetCoreCLI@2
  inputs:
    command: run
    projects: src/DotnetFoundationWeb/*.csproj
    arguments: -c $(BuildConfiguration)
  displayName: Build and Run Statiq

- publish: output
  artifact: website
  displayName: output