name: Website PR Build
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone source
      uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201

    - name: Build
      run: dotnet run --configuration Release
        
